version: '3'
services:
  web:
    build: 
      context: .
    ports:
      - "8080:8080"
    networks:
      - global
    expose: 
      - "8080"
    depends_on:
      - redis
    environment: 
      - REDIS_HOST=redis
      - REDIS_MASTER=master
  redis:
    image: redis:5.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - global
    hostname: redis
    ports:
      - "2239:6379"
    expose:
      - "2239"
    volumes:
      - redis-data:/data
volumes:
  redis-data:

networks:
  global: 